version: '3'

services:
  bojler_build:
    build: .
    container_name: bojler_build
    volumes:
      - ./dist:/root/dist
      - ./src:/root/src
    command: "npm run gulp build"

  bojler_run:
    build: .
    container_name: bojler_run
    volumes:
      - ./dist:/root/dist
      - ./src:/root/src
    command: "npm start"

  bojler_assets:
    build: .
    container_name: bojler_assets
    volumes:
      - ./dist:/root/dist
      - ./src:/root/src
    command: "npm run assets"
